<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Rhai</string>
    <key>version</key>
    <string>v0.6.1</string>
    <key>fileTypes</key>
    <array>
      <string>rhai</string>
    </array>
    <key>uuid</key>
    <string>1e76f176-ee1c-4331-a781-eb21c0da77cf</string>
    <key>scopeName</key>
    <string>source.rhai</string>
    <key>information_for_contributors</key>
    <array>
      <string>aster: galaster@foxmail.com</string>
      <string>schungx: schungx@live.com</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#core</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>core</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal-closure-labels</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-labels</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#support</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-closure</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-constant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-template-string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-language-variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-module</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-method-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-function-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-namespace</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-punctuation</string>
          </dict>
        </array>
      </dict>
      <key>literal-constant</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal-number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-language-constant</string>
          </dict>
        </array>
      </dict>
      <key>round-brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.group.braces.round</string>
            <key>begin</key>
            <string>\((?!\*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;!\*)\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.round.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>square-brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.group.braces.square</string>
            <key>begin</key>
            <string>\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.square.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.square.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>curly-brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.group.braces.curly</string>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.curly.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.brace.curly.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#round-brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#square-brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#curly-brackets</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.documentation.rhai</string>
            <key>begin</key>
            <string>/\*\*(?![/|\*])</string>
            <key>end</key>
            <string>\*/</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.block.documentation.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.rhai</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.block.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.documentation.rhai</string>
            <key>match</key>
            <string>(///)[^/].*$\n?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.documentation.rhai</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.rhai</string>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.double-slash.rhai</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.shebang.rhai</string>
            <key>match</key>
            <string>^(#!).*$\n?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.rhai</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>function-declaration-parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>variable.parameter.function.rhai</string>
                <key>match</key>
                <string>[_a-zA-Z]\w*</string>
              </dict>
              <dict>
                <key>name</key>
                <string>punctuation.separator.parameter.function.rhai</string>
                <key>match</key>
                <string>\,</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#parameters-list</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>parameters-list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.parameter.function.rhai</string>
            <key>match</key>
            <string>[_a-zA-Z]\w*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.parameter.function.rhai</string>
            <key>match</key>
            <string>\,</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
      <key>literal-module</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.import.rhai</string>
            <key>match</key>
            <string>\b(import|export|as)\b</string>
          </dict>
        </array>
      </dict>
      <key>literal-function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function.rhai</string>
            <key>begin</key>
            <string>(?x)  (?:\b(private)\s+)?
  \s*(fn)
  \s*([_a-zA-Z]\w*)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.rhai</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters-list</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>literal-closure</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function.closure.rhai</string>
            <key>begin</key>
            <string>(\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.closure.begin.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\|)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.closure.end.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters-list</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.closure.rhai</string>
            <key>begin</key>
            <string>(\b[_a-zA-Z]\w*)\s*(=)\s*(\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.closure.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.rhai</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.closure.begin.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\|)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.closure.end.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters-list</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>literal-closure-labels</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function.closure.rhai</string>
            <key>begin</key>
            <string>(\b[_a-zA-Z]\w*)\s*(\:)\s*(\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.label.rhai entity.name.function.method.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.rhai</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.closure.begin.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\|)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.closure.end.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters-list</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.closure.rhai</string>
            <key>begin</key>
            <string>((\")((?:[^"]|\\")*)(\"))\s*(:)\s*(\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.rhai</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.method.rhai</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.rhai</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.rhai</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.closure.begin.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\|)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.closure.end.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters-list</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>literal-function-call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function-call.without-arguments.rhai</string>
            <key>match</key>
            <string>(?x)  ([_a-zA-Z]\w*)(!)?\s*
  (\(\s*\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.function-call.capture.rhai</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.group.braces.round.function.arguments.rhai</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function-call.with-arguments.rhai</string>
            <key>match</key>
            <string>(?x)  ([_a-zA-Z]\w*)(!)?\s*
  (?=\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.function-call.capture.rhai</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>literal-method-call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function-call.method.without-arguments.rhai</string>
            <key>match</key>
            <string>(?x)  (?&lt;=\.)
  \s*([_a-zA-Z]\w*)\s*
  (\(\s*\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.group.braces.round.function.arguments.rhai</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function-call.method.with-arguments.rhai</string>
            <key>match</key>
            <string>(?x)  (?&lt;=\.)
  \s*([_a-zA-Z]\w*)\s*
  (?=\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rhai</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>literal-language-variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.language.this.rhai</string>
            <key>match</key>
            <string>\bthis\b</string>
          </dict>
        </array>
      </dict>
      <key>literal-language-constant</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.true.rhai</string>
            <key>match</key>
            <string>\btrue\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.false.rhai</string>
            <key>match</key>
            <string>\bfalse\b</string>
          </dict>
        </array>
      </dict>
      <key>literal-keyword-storage</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.rhai</string>
            <key>match</key>
            <string>\b(const|let)\b</string>
          </dict>
        </array>
      </dict>
      <key>literal-keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal-keyword-storage</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.rhai</string>
            <key>match</key>
            <string>\b(return)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.rhai</string>
            <key>match</key>
            <string>\b(if|else|switch)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.trycatch.rhai</string>
            <key>match</key>
            <string>\b(throw|try|catch)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.rhai</string>
            <key>match</key>
            <string>\b(for|in|loop|do|while|until|break|continue)\b</string>
          </dict>
        </array>
      </dict>
      <key>literal-operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical.rhai</string>
            <key>match</key>
            <string>(?x)  !(?!=)| # logical-not     right-to-left   right
  &amp;&amp;    | # logical-and     left-to-right   both
  \|\|    # logical-or      left-to-right   both</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.rhai</string>
            <key>match</key>
            <string>(?x)  =(?![=&gt;]) # assignment      right-to-left   both</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.augmented.rhai</string>
            <key>match</key>
            <string>(?x)  %=   | # assignment      right-to-left   both
  &amp;=   | # assignment      right-to-left   both
  \*\*=| # assignment      right-to-left   both
  (?&lt;!\*)\*= | # assignment      right-to-left   both
  \+=  | # assignment      right-to-left   both
  -=   | # assignment      right-to-left   both
  /=   | # assignment      right-to-left   both
  \^=  | # assignment      right-to-left   both
  \|=  | # assignment      right-to-left   both
  &lt;&lt;=  | # assignment      right-to-left   both
  &gt;&gt;=    # assignment      right-to-left   both</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.bitwise.rhai</string>
            <key>match</key>
            <string>(?x)  &lt;&lt;   | # bitwise-shift   left-to-right   both
  &gt;&gt;   | # bitwise-shift   left-to-right   both
  &amp;    | # bitwise-and     left-to-right   both
  \^   | # bitwise-xor     left-to-right   both
  \|     # bitwise-or      left-to-right   both</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.relational.rhai</string>
            <key>match</key>
            <string>(?x)  &lt;=     | # relational      left-to-right   both
  &gt;=     | # relational      left-to-right   both
  &lt;(?!-) | # relational      left-to-right   both
  (?&lt;!-)&gt;  # relational      left-to-right   both</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.rhai</string>
            <key>match</key>
            <string>(?x)  ==(?!=) | # equality        left-to-right   both
  !=(?!=)   # equality        left-to-right   both</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.rhai</string>
            <key>match</key>
            <string>(?x)  /         | # division        left-to-right   both
  %         | # modulus         left-to-right   both
  \*\*      | # power           left-to-right   both
  \*(?!\))  | # multiplication  left-to-right   both
  \+(?!\+)  | # addition        left-to-right   both
  -(?![&gt;-])   # subtraction     left-to-right   both</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.accessor.rhai punctuation.accessor.rhai</string>
            <key>match</key>
            <string>\.(?!\.)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.switch.case.rhai</string>
            <key>match</key>
            <string>=&gt;</string>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.operator.rhai</string>
            <key>match</key>
            <string>(\(\*|\*\)|\+\+|--|\.\.+|~|#(?!{)|@|\$(?!{)|-&gt;|&lt;-|===|!==|\:=|\:\:&lt;)</string>
          </dict>
        </array>
      </dict>
      <key>literal-labels</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)  (?&lt;!\?)(?&lt;!\?\s)
    (?=((")((?:[^\:"]|\\")*)("))\s*:)</string>
            <key>end</key>
            <string>:</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#literal-string</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.other.object.key.rhai</string>
            <key>match</key>
            <string>(?&lt;!\.|\?|\?\s)([_a-zA-Z]\w*)\s*(:)(?!\:)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.label.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.rhai</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>literal-number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.rhai</string>
            <key>match</key>
            <string>(?xi)  (?:\B[-+])?
  (?:
    \b0b[0-1][_0-1]*|           # binary
    \b0o[0-7][_0-7]*|           # octal
    \b0x[0-9a-f][_0-9a-f]*|     # hex
    (
      \B\.[0-9][_0-9]*|         # e.g. .999
      \b[0-9][_0-9]*(\.[0-9]?[_0-9]*)? # e.g. 999.999, 999. or 999
    )(e[-+]?[0-9][_0-9]*)?      # e.g. e+123
  )</string>
          </dict>
        </array>
      </dict>
      <key>literal-punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.statement.rhai</string>
            <key>match</key>
            <string>\;</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.delimiter.comma.rhai</string>
            <key>match</key>
            <string>\,</string>
          </dict>
        </array>
      </dict>
      <key>literal-template-string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.interpolated.rhai</string>
            <key>begin</key>
            <string>`</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>`</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-content</string>
              </dict>
              <dict>
                <key>name</key>
                <string>meta.interpolation.rhai</string>
                <key>begin</key>
                <string>\${</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.interpolation.begin.rhai</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>}</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.interpolation.end.rhai</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#expression</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>literal-string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.single.rhai</string>
            <key>match</key>
            <string>('([^'\\]|\\([tnr'\\]|x\h{2}|u\h{4}|U\h{8}))')</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\([tnr'\\]|x\h{2}|u\h{4}|U\h{8})</string>
                <key>name</key>
                <string>constant.character.escape.rhai</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.double.rhai</string>
            <key>begin</key>
            <string>(")</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.rhai</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.rhai</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-content</string>
              </dict>
              <dict>
                <key>name</key>
                <string>invalid.illegal.newline.rhai</string>
                <key>match</key>
                <string>(?&lt;!\\)\n</string>
              </dict>
              <dict>
                <key>name</key>
                <string>constant.character.escape.newline.rhai punctuation.separator.continuation</string>
                <key>match</key>
                <string>\\\n</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.rhai</string>
            <key>match</key>
            <string>\\(x[\da-fA-F]{2}|u[\da-fA-F]{4}|U[\da-fA-F]{8}|t|r|n|\\)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.escape.rhai</string>
            <key>match</key>
            <string>\\[^xuUtrn\\\n]</string>
          </dict>
        </array>
      </dict>
      <key>literal-namespace</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.path.rhai</string>
            <key>match</key>
            <string>([_a-zA-Z]\w*)\s*(\:\:)(?!&lt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.namespace.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.namespace.rhai</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\:\:)(\s*([_a-zA-Z]\w*))\s*(?!\:\:)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.path.rhai</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.rhai</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>literal-variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.constant.rhai</string>
            <key>match</key>
            <string>[A-Z][_\dA-Z]*\b</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!\.)\s*([_a-zA-Z]\w*)\s*(?=\.)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.object.rhai</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\.)\s*([_a-zA-Z]\w*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.property.rhai entity.name.property.rhai</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.readwrite.rhai</string>
            <key>match</key>
            <string>[_a-zA-Z]\w*</string>
          </dict>
        </array>
      </dict>
      <key>support</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.function.rhai</string>
            <key>match</key>
            <string>\b(print|debug|call|curry|eval|type_of|is_def_var|is_def_fn|is_shared)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.keyword.rhai</string>
            <key>match</key>
            <string>\b(var|static|begin|end|shared|each|then|goto|exit|unless|match|case|public|protected|new|use|with|module|package|super|thread|spawn|go|await|async|sync|yield|default|void|null|nil)\b</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>